version: "3.3"

services:
  mysql:
    container_name: mysql_desarrollo
    restart: always
    image: mysql/mysql-server:latest
    volumes:
      - /srv/mysql:/var/lib/mysql
      - /srv/mysql/mysqlconf:/etc/mysql/conf.d      
    ports:
      - "13306:3306"
    environment:
      MYSQL_ROOT_PASSWORD : 'passwordroot'     
