version: "3.3"

services:
  nginx:
    container_name: nginx
    image: nginx:latest
    volumes:
     - /srv/nginx/public_html:/usr/share/nginx/html
     - /srv/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
     - /srv/nginx/conf:/etc/nginx/conf.d
     - /srv/nginx/data/certbot/conf:/etc/letsencrypt
     - /srv/nginx/data/certbot/www:/var/www/certbot
    ports:
     - "10080:80"
     - "10443:443"
    command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"
    certbot:
      image: certbot/certbot
      volumes:
        - /srv/nginx/data/certbot/conf:/etc/letsencrypt
        - /srv/nginx/data/certbot/www:/var/www/certbot
      entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
